remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
title: Welcome to GoEPIC
description: (EPIC stands for Eric Paquin Innovation Consultant)
You will find here all the details you need to learn more about me.
